#!/usr/bin/env bash
#
# Migrate NUPROP's Redis from Upstash to a self-hosted Fly app.
#
# Spins up a new Fly app `nuprop-redis` running redis:7-alpine on a small
# always-on machine in the same region as the nuprop app, with AOF
# persistence to a Fly volume. Then rotates nuprop's REDIS_URL to point at
# the new app via Fly's internal 6PN DNS, and restarts any stopped worker
# machines (workaround for the standing bug where the worker process
# doesn't auto-restart after a secret change).
#
# Idempotent: re-running is safe. Skips app/volume creation if they exist.
# Re-deploys redis with the latest config each run.
#
# Usage:
#   bash backend/scripts/migrate_redis_to_self_hosted.sh
#
# Requires: fly CLI (authenticated), jq.
#
# After running:
#   - Verify: fly logs -a nuprop | grep -iE 'redis|arq'
#     Look for "redis connection successful" from the worker.
#   - Cancel the Upstash subscription in their dashboard once verified.
#   - Update HANDOFF.md to drop the Upstash reference.
#
# To roll back: re-run `fly secrets set -a nuprop REDIS_URL="<old-upstash-url>"`
# (retrieve the old URL from your Upstash dashboard; Fly doesn't reveal it).

set -euo pipefail

# ── Config ───────────────────────────────────────────────────────────────────
APP="${APP:-nuprop}"
REDIS_APP="${REDIS_APP:-nuprop-redis}"
REGION="${REGION:-bom}"
VOLUME_NAME="${VOLUME_NAME:-redis_data}"
VOLUME_SIZE_GB="${VOLUME_SIZE_GB:-1}"
NEW_REDIS_URL="redis://${REDIS_APP}.internal:6379/0"

# ── Pre-flight ───────────────────────────────────────────────────────────────
need() { command -v "$1" >/dev/null 2>&1 || { echo "ERROR: $1 not found in PATH"; exit 1; }; }
need fly
need jq

if ! fly auth whoami >/dev/null 2>&1; then
    echo "ERROR: not logged in to Fly. Run: fly auth login"
    exit 1
fi

# Note: Fly CLI's `apps show` was removed in recent versions; check via `apps list`.
if ! fly apps list --json | jq -e --arg n "$APP" '.[] | select(.Name == $n)' >/dev/null 2>&1; then
    echo "ERROR: target app '$APP' not found in your Fly account"
    exit 1
fi

echo "==> Account: $(fly auth whoami)"
echo "==> Migrating Redis for app '$APP' to self-hosted '$REDIS_APP' in region '$REGION'"
echo

# ── Capture current REDIS_URL digest for reference ──────────────────────────
# Note: fly secrets list --json uses lowercase keys (name, digest, status),
# whereas fly apps list --json uses TitleCase. Fly is inconsistent across endpoints.
OLD_DIGEST=$(fly secrets list -a "$APP" --json 2>/dev/null \
    | jq -r '.[] | select(.name == "REDIS_URL") | .digest' \
    || echo "")
if [[ -n "$OLD_DIGEST" ]]; then
    echo "Current REDIS_URL digest on $APP: $OLD_DIGEST"
    echo "(Fly never reveals secret values. A digest change after rotation proves the cutover.)"
else
    echo "No REDIS_URL currently set on $APP."
fi
echo

# ── Confirm ──────────────────────────────────────────────────────────────────
echo "This will:"
echo "  1. Create Fly app '$REDIS_APP' running redis:7-alpine in '$REGION'"
echo "     (idempotent — skips if already exists)"
echo "  2. Create a ${VOLUME_SIZE_GB}GB persistent volume for AOF"
echo "  3. Rotate $APP's REDIS_URL to: $NEW_REDIS_URL"
echo "  4. Restart any stopped worker machines on $APP"
echo
read -p "Proceed? [y/N] " -n 1 -r
echo
[[ $REPLY =~ ^[Yy]$ ]] || { echo "Cancelled."; exit 0; }

# ── Step 1: Create the new app ──────────────────────────────────────────────
echo
echo "==> [1/6] Creating Fly app: $REDIS_APP"
if fly apps list --json | jq -e --arg n "$REDIS_APP" '.[] | select(.Name == $n)' >/dev/null 2>&1; then
    echo "    app already exists, skipping"
else
    fly apps create "$REDIS_APP"
fi

# ── Step 2: Create the volume ───────────────────────────────────────────────
echo
echo "==> [2/6] Creating persistent volume: $VOLUME_NAME (${VOLUME_SIZE_GB}GB) in $REGION"
EXISTING_VOL_ID=$(fly volumes list -a "$REDIS_APP" --json 2>/dev/null \
    | jq -r --arg name "$VOLUME_NAME" --arg region "$REGION" \
        '.[] | select(.name == $name and .region == $region) | .id' \
    || echo "")
if [[ -n "$EXISTING_VOL_ID" ]]; then
    echo "    volume $EXISTING_VOL_ID already exists in $REGION, skipping"
else
    fly volumes create "$VOLUME_NAME" \
        --region "$REGION" \
        --size "$VOLUME_SIZE_GB" \
        --app "$REDIS_APP" \
        --yes
fi

# ── Step 3: Generate Dockerfile + fly.toml ──────────────────────────────────
echo
echo "==> [3/6] Generating Fly config in /tmp/$REDIS_APP"
WORK_DIR="/tmp/$REDIS_APP"
mkdir -p "$WORK_DIR"

cat > "$WORK_DIR/Dockerfile" <<'EOF'
FROM redis:7-alpine

# Run as the redis user (default in the upstream image) and persist AOF to
# the mounted volume at /data. --protected-mode no is safe because this
# machine is only reachable via Fly's private 6PN network — never exposed
# to the public internet.
CMD ["redis-server", \
     "--appendonly", "yes", \
     "--dir", "/data", \
     "--protected-mode", "no"]
EOF

cat > "$WORK_DIR/fly.toml" <<EOF
# Auto-generated by migrate_redis_to_self_hosted.sh — regenerate by re-running
# the script. Manual edits will be overwritten.
app = '$REDIS_APP'
primary_region = '$REGION'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = '$VOLUME_NAME'
  destination = '/data'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1

# No [http_service] — Redis is reachable only via Fly's internal 6PN at
# ${REDIS_APP}.internal:6379. Never publish 6379 to the public internet.
EOF

# ── Step 4: Deploy ───────────────────────────────────────────────────────────
echo
echo "==> [4/6] Deploying redis:7-alpine to $REDIS_APP (first deploy takes ~2-3 min)"
(cd "$WORK_DIR" && fly deploy --remote-only)

# Brief settling time so .internal DNS propagates before the app tries to use it.
echo
echo "==> Waiting 10s for Fly internal DNS to propagate..."
sleep 10

echo
echo "==> $REDIS_APP machine status:"
fly status -a "$REDIS_APP"

# ── Step 5: Rotate REDIS_URL on the target app ──────────────────────────────
echo
echo "==> [5/6] Setting REDIS_URL on $APP"
echo "    New URL: $NEW_REDIS_URL"
fly secrets set -a "$APP" REDIS_URL="$NEW_REDIS_URL"

# ── Step 6: Restart any stopped worker machines ─────────────────────────────
echo
echo "==> [6/6] Restarting stopped worker machines on $APP"
echo "    (Workaround for the standing bug where worker process doesn't"
echo "     auto-restart after secret changes — see HANDOFF.)"
sleep 5  # let Fly settle from the secret-set rolling restart
STOPPED_WORKERS=$(fly machine list -a "$APP" --json \
    | jq -r '.[] | select(.config.metadata.fly_process_group == "worker" and .state == "stopped") | .id')
if [[ -z "$STOPPED_WORKERS" ]]; then
    echo "    no stopped workers, skipping"
else
    while IFS= read -r id; do
        [[ -z "$id" ]] && continue
        echo "    starting worker $id"
        fly machine start "$id" -a "$APP" || echo "    WARNING: failed to start $id"
    done <<< "$STOPPED_WORKERS"
fi

# ── Done ─────────────────────────────────────────────────────────────────────
echo
echo "==> Final $APP status:"
fly status -a "$APP"

echo
echo "════════════════════════════════════════════════════════════════════════"
echo " Migration complete. Next steps:"
echo
echo "  1. Tail logs and verify ARQ connects to the new Redis:"
echo "       fly logs -a $APP | grep -iE 'redis|arq'"
echo "     You should see: 'redis connection successful'"
echo "     You should NOT see: 'max requests limit exceeded'"
echo
echo "  2. Smoke-test the app: send a chat message, watch a pipeline phase run."
echo
echo "  3. Once verified working for ~24h, cancel the Upstash subscription"
echo "     in their dashboard. The new Redis is on Fly's private network only."
echo
echo "  4. Update docs/superpowers/HANDOFF.md to drop the Upstash reference."
echo
echo " To roll back if needed:"
echo "    fly secrets set -a $APP REDIS_URL='<old-upstash-url-from-your-records>'"
echo "    fly apps destroy $REDIS_APP   # only after confirming rollback works"
echo "════════════════════════════════════════════════════════════════════════"
