"""Pass-1 fact-section generators.

Each fact section is generated by a single LLM call that is independent of the
other fact sections (so the seven calls fan out concurrently). The shared
``generate_fact_section`` function dispatches to a per-type ``PromptBuilder`` —
one entry per fact section — which owns its system prompt, user-prompt
construction, and optional metadata-extraction logic.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Callable

from app.services.llm import Tier, get_ai_service

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PromptBuilder:
    system: str
    user_template: Callable[..., str]
    metadata_fn: Callable[[str, dict], dict] | None = None


def _build_inputs_block(
    brief: dict,
    research: str | None,
    cost_model: dict | None,
    context_brief: str | None,
    agency_name: str,
) -> str:
    payload: dict = {
        "agency_name": agency_name,
        "brief": brief or {},
    }
    if research:
        payload["research_summary"] = research[:8000]
    if cost_model:
        payload["cost_model"] = {
            "total": cost_model.get("total"),
            "line_items": cost_model.get("line_items", []),
            "tiered": cost_model.get("tiered", {}),
            "multipliers_applied": cost_model.get("multipliers_applied", []),
        }
    if context_brief:
        payload["client_context"] = context_brief[:4000]
    return json.dumps(payload, ensure_ascii=False, indent=2)


def _user_for_problem_statement(brief, research, cost_model, context_brief, agency_name) -> str:
    inputs = _build_inputs_block(brief, research, cost_model, context_brief, agency_name)
    return (
        "Inputs:\n```json\n" + inputs + "\n```\n\n"
        "Write the PROBLEM STATEMENT / NEEDS ASSESSMENT section of a proposal."
        " 2-4 short paragraphs in markdown. Demonstrate you understand the client's"
        " situation, pain point, or opportunity. Use details from the brief and"
        " client_context. Do not pitch the solution here; do not talk about the"
        " agency. Be specific to this client, not generic."
    )


def _user_for_proposed_solution(brief, research, cost_model, context_brief, agency_name) -> str:
    inputs = _build_inputs_block(brief, research, cost_model, context_brief, agency_name)
    return (
        "Inputs:\n```json\n" + inputs + "\n```\n\n"
        "Write the PROPOSED SOLUTION / APPROACH section. 3-5 paragraphs in markdown."
        " What you'll actually do, how, and why this approach. If natural, break into"
        " sub-headings for phases, methodology, or workstreams. Reference the brief's"
        " deliverables. Avoid generic language; be specific to this engagement."
    )


def _user_for_scope_of_work(brief, research, cost_model, context_brief, agency_name) -> str:
    inputs = _build_inputs_block(brief, research, cost_model, context_brief, agency_name)
    return (
        "Inputs:\n```json\n" + inputs + "\n```\n\n"
        "Write the SCOPE OF WORK / DELIVERABLES section. List the concrete outputs"
        " the client receives, as a markdown bulleted list grouped by category."
        " Where useful, also list explicit exclusions ('not included') to manage"
        " expectations. Use the brief's `project.deliverables` and the cost_model's"
        " `line_items` as the source of truth."
    )


def _user_for_timeline(brief, research, cost_model, context_brief, agency_name) -> str:
    inputs = _build_inputs_block(brief, research, cost_model, context_brief, agency_name)
    return (
        "Inputs:\n```json\n" + inputs + "\n```\n\n"
        "Write the TIMELINE / SCHEDULE section. Express as a markdown table with"
        " columns Phase | Duration | Milestone. Derive phases from the proposed"
        " solution / scope. If the brief specifies dates or a start window, anchor"
        " to them; otherwise express as relative durations (e.g. 'Week 1-3')."
    )


def _user_for_pricing(brief, research, cost_model, context_brief, agency_name) -> str:
    inputs = _build_inputs_block(brief, research, cost_model, context_brief, agency_name)
    return (
        "Inputs:\n```json\n" + inputs + "\n```\n\n"
        "Write the PRICING / BUDGET section. Lead with a one-paragraph summary of"
        " total cost and what's included, then a markdown table of line items"
        " (Item | Description | Cost in INR). If cost_model.tiered is non-empty,"
        " also describe each tier briefly. Conclude with payment structure if"
        " present in the brief. Be transparent about what's and isn't included."
    )


def _pricing_metadata(_text: str, cost_model: dict | None) -> dict:
    if not cost_model:
        return {}
    return {
        "total": cost_model.get("total"),
        "line_item_count": len(cost_model.get("line_items", [])),
        "tiered": bool(cost_model.get("tiered")),
    }


def _user_for_qualifications(brief, research, cost_model, context_brief, agency_name) -> str:
    inputs = _build_inputs_block(brief, research, cost_model, context_brief, agency_name)
    return (
        "Inputs:\n```json\n" + inputs + "\n```\n\n"
        "Write the QUALIFICATIONS / ABOUT US section for " + agency_name + "."
        " 2-3 short paragraphs in markdown. Cover: relevant experience for this"
        " kind of work, key team capabilities, and one or two specific past"
        " results if any can be inferred from the inputs. Avoid generic agency"
        " puffery — be concrete, specific, and short. If client_context mentions"
        " prior work with this client, lead with that."
    )


def _user_for_terms_and_conditions(brief, research, cost_model, context_brief, agency_name) -> str:
    inputs = _build_inputs_block(brief, research, cost_model, context_brief, agency_name)
    return (
        "Inputs:\n```json\n" + inputs + "\n```\n\n"
        "Write the TERMS AND CONDITIONS section. Markdown, concise. Cover:"
        " payment terms (use cost_model.tiered.payment_terms or a sensible default"
        " like '50% on signing, 50% on delivery'), validity period (30 days from"
        " issuance), IP ownership (deliverables transfer to client on full"
        " payment), revisions included (use cost_model.standard_revisions if"
        " present, default 2), and a short cancellation clause. Keep it readable"
        " — clients shouldn't need a lawyer to parse it."
    )


PROMPT_BUILDERS: dict[str, PromptBuilder] = {
    "problem_statement": PromptBuilder(
        system="You are a senior proposal writer for a creative agency. Write the requested section directly — no preamble, no meta-commentary, no 'Here is...' lead-in.",
        user_template=_user_for_problem_statement,
    ),
    "proposed_solution": PromptBuilder(
        system="You are a senior proposal writer. Write directly; no preamble.",
        user_template=_user_for_proposed_solution,
    ),
    "scope_of_work": PromptBuilder(
        system="You are a senior proposal writer. Write a markdown bulleted scope-of-work directly; no preamble.",
        user_template=_user_for_scope_of_work,
    ),
    "timeline": PromptBuilder(
        system="You are a senior proposal writer. Output a markdown table only; no preamble or trailing prose.",
        user_template=_user_for_timeline,
    ),
    "pricing": PromptBuilder(
        system="You are a senior proposal writer. Output the pricing section in markdown directly; no preamble.",
        user_template=_user_for_pricing,
        metadata_fn=_pricing_metadata,
    ),
    "qualifications": PromptBuilder(
        system="You are a senior proposal writer. Write directly; no preamble; no generic agency puffery.",
        user_template=_user_for_qualifications,
    ),
    "terms_and_conditions": PromptBuilder(
        system="You are a senior proposal writer. Write the T&C section in markdown directly; no preamble.",
        user_template=_user_for_terms_and_conditions,
    ),
}


async def generate_fact_section(
    section_type: str,
    brief: dict,
    research: str | None,
    cost_model: dict | None,
    template_config: dict | None,
    context_brief: str | None,
    agency_name: str,
) -> dict:
    """Generate one fact section and return its payload dict."""
    builder = PROMPT_BUILDERS[section_type]
    user_prompt = builder.user_template(brief, research, cost_model, context_brief, agency_name)

    result = await get_ai_service().complete(
        prompt=user_prompt,
        system=builder.system,
        tier=Tier.BALANCED,
        max_tokens=2000,
    )

    metadata: dict = {}
    if builder.metadata_fn:
        metadata = builder.metadata_fn(result.text, cost_model or {})

    return {
        "content": result.text,
        "assets": [],
        "included": True,
        "metadata": metadata,
    }
